name: Install Dependencies
description: Install dependencies
inputs:
    destination:
        description: Location to check out rust-lightning and ldk-c-bindings repositories
        default: '.'
        required: true
    configureRustNightly:
        description: Flag whether or not to install rust, which is not necessary on Ubuntu machines
        default: 'true'
        required: false
runs:
    using: composite
    steps:
        -   name: Install Homebrew Dependencies
            shell: bash
            if: ${{ runner.os == 'macOS' }}
            run: |
                brew install gnu-sed
        -   name: Checkout Rust-Lightning and LDK-C-Bindings git
            shell: bash
            run: |
                echo `pwd`
                mkdir -p ${{ inputs.destination }}/bin
                git clone --branch 0.0.118-bindings https://github.com/lightningdevkit/rust-lightning ${{ inputs.destination }}/rust-lightning
                git clone --branch main https://github.com/lightningdevkit/ldk-c-bindings ${{ inputs.destination }}/ldk-c-bindings
        -   name: Install Rust, required targets
            if: ${{ inputs.configureRustNightly == 'true' }}
            shell: bash
            run: |
                rustup toolchain install nightly-2022-05-13
                rustup target add aarch64-apple-darwin aarch64-apple-ios x86_64-apple-ios
                rustup component add rust-src --toolchain nightly-2022-05-13-x86_64-apple-darwin
        -   name: Load Cache
            if: ${{ inputs.configureRustNightly == 'true' }}
            uses: actions/cache@v3
            with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        -   name: Pin cbindgen v24
            shell: bash
            run: |
                cargo install --version 0.24.5 cbindgen
        -   name: Generate C Bindings
            shell: bash
            run: |
                export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
                pushd ${{ inputs.destination }}/ldk-c-bindings
                ./genbindings.sh ../rust-lightning true
                popd
