name: Install Dependencies
runs:
  using: composite
  steps:
  - name: Install Homebrew Dependencies
    shell: bash
    run: |
      brew install gnu-sed
  - name: Checkout Rust-Lightning and LDK-C-Bindings git
    shell: bash
    run: |
      git clone --branch 2021-03-java-bindings-base https://github.com/TheBlueMatt/rust-lightning bindings/artifacts/rust-lightning
      git clone https://github.com/lightningdevkit/ldk-c-bindings bindings/artifacts/ldk-c-bindings
  - name: Install Rust, required targets
    shell: bash
    run: |
      rustup toolchain install nightly
      rustup target add aarch64-apple-darwin aarch64-apple-ios x86_64-apple-ios
      rustup component add rust-src --toolchain nightly-x86_64-apple-darwin
  - name: Load Cache
    uses: actions/cache@v3
    with:
      path: |
        ~/.cargo/bin/
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/db/
        target/
      key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  - name: Generate C Bindings
    shell: bash
    run: |
      export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
      pushd bindings/artifacts/ldk-c-bindings
      ./genbindings.sh ../rust-lightning true
      popd
  - name: Generate Swift Bindings
    shell: bash
    run: |
      python3 ./
    env:
      LDK_SWIFT_GENERATOR_INPUT_HEADER_PATH: bindings/artifacts/ldk-c-bindings/lightning-c-bindings/include/lightning.h
