name: Build For Testing
inputs:
  scheme:
    description: Scheme
    required: true
  destination:
    description: Destination
    required: true
  workspace:
    description: Workspace Name
    required: true
runs:
  using: composite
  steps:
  - shell: bash
    working-directory: .
    run: |
      cd xcode

      xcodebuild clean build-for-testing \
        -allowProvisioningUpdates \
        -allowProvisioningDeviceRegistration \
        -workspace '${{ inputs.workspace }}' \
        -scheme '${{ inputs.scheme }}' \
        -destination '${{ inputs.destination }}' \
        -resultBundlePath BuildResults.xcresult \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
