name: Test Without Building
inputs:
  scheme:
    description: Scheme
    required: true
  destination:
    description: Destination
    required: true
  test-plan:
    description: Test Plan
    required: false
  artifact-prefix:
    description: The prefix for the filename of the uploaded xcresults file
    required: true
  check-name:
    description: The check name
    required: true
  project:
    description: Project directory, relative to the xcode folder
    required: true
runs:
  using: composite
  steps:
  - shell: bash
    id: vars
    run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
  - shell: bash
    working-directory: .
    run: |
      cd xcode

      xcodebuild test-without-building \
      -project '${{ inputs.project }}' \
      -scheme '${{ inputs.scheme }}' \
      -destination '${{ inputs.destination }}' \
      -resultBundlePath "${{ inputs.artifact-prefix }}-${{ steps.vars.outputs.sha_short }}.xcresult"
  - uses: kishikawakatsumi/xcresulttool@v1
    if: always()
    with:
      path: ./xcode/${{ inputs.artifact-prefix }}-${{ steps.vars.outputs.sha_short }}.xcresult
      title: ${{ inputs.check-name }}
      show-passed-tests: false
