name: DirectBindingsApp
permissions:
  contents: read
  statuses: read
  pull-requests: read
  actions: read
  checks: write
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - "*"

jobs:
  build:
    name: Build (${{ matrix.configuration['scheme'] }} - ${{ matrix.configuration['platform'] }})
    runs-on: macos-12
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        configuration:
        - scheme: DirectBindingsApp
          destination: platform=iOS Simulator,OS=15.4,name=iPhone 13 Pro
          platform: iOS Simulator
          project: DirectBindingsApp/DirectBindingsApp.xcodeproj
        - scheme: DirectBindingsAppTests
          destination: platform=iOS Simulator,OS=15.4,name=iPhone 13 Pro
          platform: iOS Simulator
          project: DirectBindingsApp/DirectBindingsApp.xcodeproj
          xcode-unit-test: DirectBindingsAppTests
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.3.1.app/Contents/Developer
    steps:
    - name: Configure Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      uses: ./.github/actions/install-dependencies
    - name: Build
      id: build
      uses: ./.github/actions/build-for-testing
      with:
        project: ${{ matrix.configuration['project'] }}
        scheme: ${{ matrix.configuration['scheme'] }}
        destination: ${{ matrix.configuration['destination'] }}
    - name: Xcode Unit Test
      if: ${{ matrix.configuration['xcode-unit-test'] != '' }}
      continue-on-error: true
      uses: ./.github/actions/test-without-building
      with:
        project: ${{ matrix.configuration['project'] }}
        scheme: ${{ matrix.configuration['scheme'] }}
        destination: ${{ matrix.configuration['destination'] }}
        test-plan: ${{ matrix.configuration['xcode-unit-test'] }}
        artifact-prefix: unit-tests-${{ matrix.configuration['sdk-name'] }}
        check-name: Xcode Unit Tests (${{ matrix.configuration['platform'] }})
