name: Release Framework
permissions:
  contents: write
  statuses: read
  pull-requests: read
  actions: read
  checks: write
on:
  push:
    tags:
      - "*"

jobs:
  archive:
    name: Archive Frameworks (${{ matrix.configuration['platform'] }})
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        configuration:
        - scheme: LDKFramework
          destination: generic/platform=iOS
          platform: iOS
          project: LDK/LightningDevKit.xcodeproj
        - scheme: LDKFramework
          destination: generic/platform=iOS Simulator
          platform: iOS Simulator
          project: LDK/LightningDevKit.xcodeproj
        - scheme: LDKFramework_Mac
          destination: generic/platform=OS X
          platform: Darwin
          project: LDK/LightningDevKit.xcodeproj
        - scheme: LDKFramework
          destination: generic/platform=macOS
          platform: Catalyst
          project: LDK/LightningDevKit.xcodeproj
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
      BUILD_DIR: ./build
      LDK_C_BINDINGS_BASE: /Users/runner/work/ldk-swift/ldk-swift/bindings/artifacts/ldk-c-bindings
      LDK_C_BINDINGS_BINARY_DIRECTORY: /Users/runner/work/ldk-swift/ldk-swift/bindings/artifacts/bin
    steps:
    - name: Configure Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      uses: ./.github/actions/install-dependencies
    - name: Archive
      uses: ./.github/actions/archive-framework
      with:
        project: ${{ matrix.configuration['project'] }}
        scheme: ${{ matrix.configuration['scheme'] }}
        destination: ${{ matrix.configuration['destination'] }}
        platform: ${{ matrix.configuration['platform'] }}
    - name: Upload Archive
      uses: actions/upload-artifact@v3
      with:
        name: LDKFramework-${{ matrix.configuration['platform'] }}.xcarchive
        path: |
          ./xcode/build/LDKFramework-${{ matrix.configuration['platform'] }}.xcarchive
  create-xcframework:
    name: Create Fat Framework
    runs-on: macos-12
    needs: [archive]
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
      BUILD_DIR: ./build
    steps:
      - name: Download xcarchives
        uses: actions/download-artifact@v3
      - name: Create xcframework and release
        run: |
          xcodebuild -create-xcframework \
            -framework LDKFramework-iOS.xcarchive/Products/Library/Frameworks/LDKFramework.framework \
            -framework LDKFramework-iOS\ Simulator.xcarchive/Products/Library/Frameworks/LDKFramework.framework \
            -framework LDKFramework-Catalyst.xcarchive/Products/Library/Frameworks/LDKFramework.framework \
            -framework LDKFramework-Darwin.xcarchive/Products/Library/Frameworks/LDKFramework_Mac.framework \
            -output LDKFramework.xcframework
      - name: Zip Xcframework
        run: |
          zip -r LDKFramework.xcframework.zip LDKFramework.xcframework
      - name: Upload Framework Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LDKFramework.xcframework.zip
          path: LDKFramework.xcframework.zip
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [create-xcframework]
    steps:
      - name: Download Framework Artifact
        uses: actions/download-artifact@v3
        with:
          name: LDKFramework.xcframework.zip
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: LDKFramework.xcframework.zip
